spring.application.name=memo

spring.datasource.url=jdbc:postgresql://localhost:5432/memo_db
spring.datasource.username=postgres
spring.datasource.password=244110
spring.jpa.hibernate.ddl-auto=update


